# Generated by Django 3.2 on 2023-11-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231125_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
